name: CI/CD Pipeline for Python

on:
  push:
    branches:
      - main  # Déclenche le pipeline sur un push vers la branche main
  pull_request:
    branches:
      - main  # Déclenche le pipeline sur une pull request vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Remplacez par la version de Python que vous utilisez

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest  # Exécute les tests avec pytest

#      - name: Run linting
#        run: |
#          pip install flake8  # Installe flake8 pour le linting
#          flake8 .  # Exécute flake8 pour vérifier le style du code

  deploy:
    runs-on: ubuntu-latest
    needs: test  # S'assure que le déploiement ne se fait que si les tests réussissent
    if: github.ref == 'refs/heads/main'  # Déploie uniquement sur la branche main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

